services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_APP_VERSION: ${VITE_APP_VERSION}
    restart: unless-stopped
    expose:
      - "80"